language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: draumateimid
  api_key:
    secure: XHWw2ils2PIYb7VAGdhA1vIeGjcY9fBW012HsEJY6CVHwAhXbPSdFy4d3Lj10is78wvLtd4MSIDdXpbX30q8zjcPGMGgDHTVbYZY7Tw1/kYUlfvm5EdkhfYxMNShkqKwL2JVB8MSfFvnvI12l9v5g8RTLYyqHqIoxOVxHtg+4Q5pXmSPunKdPEIabMPdMk8tSGJ8ktWCu9/+MNCmbhqF4tvrxJoEnhzABPUrUPw6/6woWpvoDsje69u697StPbw9XUIqshIxPPYTefPqq0k6ZJYA0Wpfrz9UcvsRSeVt7fc9Qkzb6HtkZ/XZA9lPG7KXfq9FaOPtfolCaI6qnqlz1m6E7e4+OiwORjZfnHxiqws1IWVA2vKcBscjojhBozr5kGPgW5wfF+Nyt5q/hVOvP41e2gXLFq0+sUHkDJILrP9kjrqhY53NBN5oXSCLAhzWJqj1BszpyGXHMk70OClsy/09rDlmbCLZsB4x6fE2dyFJykGmYBhoFio1A1wDg81cWZzWSstHV+qDv51d/ae8IzP8xBPX8odJpEm0jZCzUZkPGpDU0yrcRnjbaDmppVSj2jV4iYlNSs+T7JC58yrTbf8iUvmdau2RE/tHUgn5NY7QhOoQtfdLJml9QHzghiDYfS9LN0MbeEIMZTeCNJruKI6M7375+v7U5FHad8wNAzM=
